language: node_js
node_js:
    - '0.10'
env:
    - DISPLAY=":99.0"
before_install:
    - "sh -e /etc/init.d/xvfb start"
install:
    - 'npm install'
    - 'npm install -g grunt-cli'
    - 'gem install compass'
script:
    - 'grunt test_travis'