language: node_js
node_js:
    - '0.10'
before_install:
    - 'rm -rf node_modules'
install:
    - 'npm install'
before_script:
    - 'npm install -g grunt-cli'
    - 'gem install compass'
script:
    - 'grunt test'

