language: node_js
node_js:
    - '0.10'
env:
    - DISPLAY=":99.0"
before_install:
    - "sh -e /etc/init.d/xvfb start"
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
    - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
    - sudo apt-get update
    - sudo apt-get install google-chrome-stable
install:
    - 'npm install'
    - 'npm install -g grunt-cli'
    - 'node_modules/protractor/bin/webdriver-manager update --chrome'
    - 'gem install compass'
script:
    - 'grunt test'

